# 년, 월, 성별 별로 상품을 구매한 회원수
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID AND NOT U.GENDER IS NULL
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR, MONTH, GENDER
