

SELECT A.CAR_ID, A.CAR_TYPE, ROUND((DAILY_FEE)*((100-DISCOUNT_RATE)/100)*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
    AND C.DURATION_TYPE = '30일 이상'
WHERE A.CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE END_DATE > '2022-11-00'
                       AND START_DATE < '2022-12-00')
GROUP BY CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
