SELECT C.APNT_NO, A.PT_NAME, C.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM PATIENT A 
    INNER JOIN APPOINTMENT C ON A.PT_NO = C.PT_NO
    INNER JOIN DOCTOR B ON B.MCDP_CD = C.MCDP_CD AND B.DR_ID = C.MDDR_ID
WHERE DATE(C.APNT_YMD) = '2022-04-13' AND C.APNT_CNCL_YMD IS NULL AND C.MCDP_CD = 'CS'
ORDER BY APNT_YMD